version: '2'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017

  dropw-ms-shortener:
    image: openjdk:8-jre
    container_name: dropw-ms-shortener
    volumes:
    - ./urlShortener/target/urlShortener-1.0.jar:/microservice/urlShortener-1.0.jar
    - ./urlShortener/config.yml:/microservice/config.yml
    working_dir: /microservice
    command: ["java", "-jar", "urlShortener-1.0.jar", "server", "config.yml"]
    ports:
    - "84:84"
    
  dropw-ms-fetcher:
    image: openjdk:8-jre
    container_name: dropw-ms-fetcher
    volumes:
    - ./urlFetcher/target/urlFetcher-1.0.jar:/microservice/urlFetcher-1.0.jar
    - ./urlFetcher/config.yml:/microservice/config.yml
    working_dir: /microservice
    command: ["java", "-jar", "urlFetcher-1.0.jar", "server", "config.yml"]
    ports:
    - "82:82"
