version: '2'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - dropw-mongodb-ntw

  dropw-ms:
    image: openjdk:8-jre
    container_name: dropw-ms
    volumes:
    - ./csc496-shortener/target/urlShortener-1.0.jar:/microservice/urlShortener-1.0.jar
    - ./csc496-shortener/config.yml:/microservice/config.yml
    working_dir: /microservice
    command: ["java", "-jar", "urlShortener-1.0.jar", "server", "config.yml"]
    ports:
    - "80:8081"
    networks:
    - dropw-mongodb-ntw

networks:
  dropw-mongodb-ntw:
    external:
      name: dropw-mongodb-ntw
